CXX = cl.exe
CFLAGS = /nologo /O2 /EHsc /D "_CRT_SECURE_NO_DEPRECATE" /D "USEOMP" /openmp

TARGET = windows

all: $(TARGET) $(TARGET)\bh_tsne.exe

$(TARGET)\bh_tsne.exe: tsne_bin.obj
	$(CXX) $(CFLAGS) tsne_bin.obj -Fe$(TARGET)\bh_tsne.exe

tsne.obj: tsne_bin.cpp tsne.h sptree.h vptree.h
	$(CXX) $(CFLAGS) -c tsne_bin.cpp

.PHONY: $(TARGET)
$(TARGET):
	-mkdir $(TARGET)

clean:
	-erase /Q *.obj *.exe $(TARGET)\.
	-rd $(TARGET)
